######################################################################
##
## Filename: DA_TLC5620.udo
## Created on: Wed Oct 18 21:40:13 中国标准时间 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
