######################################################################
##
## Filename: DA_TLC5620_tb.udo
## Created on: Wed Oct 18 22:41:45 中国标准时间 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
