######################################################################
##
## Filename: DA_TCL5620_tb.udo
## Created on: Wed Oct 18 19:48:25 中国标准时间 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
